# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Parse Dashboard for iOS.xcworkspace", scheme: "Parse Dashboard for iOS")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
